package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"

	"github.com/elc49/copod/graph/model"
	"github.com/elc49/copod/paystack"
)

// CreateUploads is the resolver for the createUploads field.
func (r *mutationResolver) CreateUploads(ctx context.Context, input []*model.UploadInput) (*bool, error) {
	b := false
	return &b, nil
}

// ChargeMpesa is the resolver for the chargeMpesa field.
func (r *mutationResolver) ChargeMpesa(ctx context.Context, input model.PayWithMpesaInput) (*string, error) {
	charge := paystack.MpesaCharge{
		Email:    input.Email,
		Reason:   input.Reason.String(),
		Currency: input.Currency,
	}

	res, err := r.paystack.ChargeMpesa(ctx, charge)
	if err != nil {
		return nil, err
	}

	return &res.Data.Reference, nil
}

// GetLocalLands is the resolver for the getLocalLands field.
func (r *queryResolver) GetLocalLands(ctx context.Context) ([]*model.Land, error) {
	return make([]*model.Land, 0), nil
}

// GetUserLands is the resolver for the getUserLands field.
func (r *queryResolver) GetUserLands(ctx context.Context, walletAddress string) ([]*model.Land, error) {
	return make([]*model.Land, 0), nil
}

// HasPendingLandRecords is the resolver for the hasPendingLandRecords field.
func (r *queryResolver) HasPendingLandRecords(ctx context.Context, walletAddress string) (bool, error) {
	return false, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
