CREATE TABLE IF NOT EXISTS uploads(
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  email TEXT NOT NULL,
  public_address TEXT NOT NULL,
  type TEXT NOT NULL,
  uri TEXT NOT NULL,
  verification TEXT NOT NULL DEFAULT 'ONBOARDING',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
