CREATE TABLE IF NOT EXISTS users(
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  firstname TEXT NOT NULL DEFAULT '',
  lastname TEXT NOT NULL DEFAULT '',
  govt_id TEXT NOT NULL,
  email TEXT NOT NULL,
  wallet_address TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_email ON users(email);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_wallet ON users(wallet_address);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_govt_id ON users(govt_id);

CREATE TABLE IF NOT EXISTS lands(
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  title TEXT NOT NULL DEFAULT '',
  size FLOAT NOT NULL DEFAULT 0.0,
  symbol VARCHAR(5) NOT NULL DEFAULT '',
  verified TEXT NOT NULL DEFAULT 'ONBOARDING',
  govt_id TEXT REFERENCES users(govt_id),
  paid_for TEXT NOT NULL DEFAULT 'PAID',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_lands_govt_id ON lands(govt_id);

CREATE TABLE IF NOT EXISTS uploads(
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  type TEXT NOT NULL,
  title_doc TEXT,
  govt_id TEXT,
  verification TEXT NOT NULL DEFAULT 'ONBOARDING',
  email TEXT NOT NULL REFERENCES users(email),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_upload_email ON uploads(email);

CREATE TABLE IF NOT EXISTS payments(
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  email TEXT NOT NULL,
  amount INTEGER NOT NULL,
  currency TEXT NOT NULL,
  reason TEXT NOT NULL,
  status TEXT NOT NULL,
  reference_id TEXT NOT NULL,
  upload_id UUID REFERENCES uploads(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_reference_id ON payments(reference_id);
