DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS titles CASCADE;
DROP TABLE IF EXISTS support_docs CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS onboardings CASCADE;
DROP TABLE IF EXISTS display_pictures;
