CREATE TABLE IF NOT EXISTS users(
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  firstname TEXT NOT NULL DEFAULT '',
  lastname TEXT NOT NULL DEFAULT '',
  govt_id TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL,
  wallet_address TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_email ON users(email);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_wallet ON users(wallet_address);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_govt_id ON users(govt_id);

CREATE TABLE IF NOT EXISTS lands(
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  title TEXT NOT NULL,
  size FLOAT NOT NULL DEFAULT 0.0,
  symbol VARCHAR(5) NOT NULL DEFAULT '',
  verified TEXT NOT NULL DEFAULT 'ONBOARDING',
  govt_id TEXT NOT NULL REFERENCES users(govt_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_lands_govt_id ON lands(govt_id);

CREATE TABLE IF NOT EXISTS uploads(
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  type TEXT NOT NULL,
  uri TEXT NOT NULL,
  verification TEXT NOT NULL DEFAULT 'ONBOARDING',
  land_id UUID REFERENCES lands(id) ON DELETE CASCADE,
  wallet_address TEXT REFERENCES users(wallet_address) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_upload_wallet ON uploads(wallet_address);
CREATE INDEX IF NOT EXISTS idx_upload_land_id ON uploads(land_id);
