// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sql

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Land struct {
	ID        uuid.UUID      `json:"id"`
	Title     string         `json:"title"`
	Size      float64        `json:"size"`
	Symbol    string         `json:"symbol"`
	Verified  string         `json:"verified"`
	GovtID    sql.NullString `json:"govt_id"`
	PaidFor   string         `json:"paid_for"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Payment struct {
	ID          uuid.UUID     `json:"id"`
	Email       string        `json:"email"`
	Amount      int32         `json:"amount"`
	Currency    string        `json:"currency"`
	Reason      string        `json:"reason"`
	Status      string        `json:"status"`
	ReferenceID string        `json:"reference_id"`
	UploadID    uuid.NullUUID `json:"upload_id"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
}

type Upload struct {
	ID            uuid.UUID `json:"id"`
	Type          string    `json:"type"`
	Uri           string    `json:"uri"`
	Verification  string    `json:"verification"`
	WalletAddress string    `json:"wallet_address"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type User struct {
	ID            uuid.UUID `json:"id"`
	Firstname     string    `json:"firstname"`
	Lastname      string    `json:"lastname"`
	GovtID        string    `json:"govt_id"`
	Email         string    `json:"email"`
	WalletAddress string    `json:"wallet_address"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}
