// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sql

import (
	"time"

	"github.com/google/uuid"
)

type Upload struct {
	ID            uuid.UUID `json:"id"`
	Email         string    `json:"email"`
	PublicAddress string    `json:"public_address"`
	Type          string    `json:"type"`
	Uri           string    `json:"uri"`
	Verification  string    `json:"verification"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}
