// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: onboarding.sql

package sql

import (
	"context"

	"github.com/google/uuid"
)

const createOnboarding = `-- name: CreateOnboarding :one
INSERT INTO onboardings (
  title_id, support_doc_id, display_picture_id, email
) VALUES (
  $1, $2, $3, $4
) RETURNING id, title_id, support_doc_id, display_picture_id, email, verification, created_at, updated_at
`

type CreateOnboardingParams struct {
	TitleID          uuid.UUID `json:"title_id"`
	SupportDocID     uuid.UUID `json:"support_doc_id"`
	DisplayPictureID uuid.UUID `json:"display_picture_id"`
	Email            string    `json:"email"`
}

func (q *Queries) CreateOnboarding(ctx context.Context, arg CreateOnboardingParams) (Onboarding, error) {
	row := q.db.QueryRowContext(ctx, createOnboarding,
		arg.TitleID,
		arg.SupportDocID,
		arg.DisplayPictureID,
		arg.Email,
	)
	var i Onboarding
	err := row.Scan(
		&i.ID,
		&i.TitleID,
		&i.SupportDocID,
		&i.DisplayPictureID,
		&i.Email,
		&i.Verification,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
