// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sql

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDisplayPicture(ctx context.Context, arg CreateDisplayPictureParams) (DisplayPicture, error)
	CreateOnboarding(ctx context.Context, arg CreateOnboardingParams) (Onboarding, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateSupportDoc(ctx context.Context, arg CreateSupportDocParams) (SupportDoc, error)
	CreateTitle(ctx context.Context, arg CreateTitleParams) (TitleDeed, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetDisplayPictureByID(ctx context.Context, id uuid.UUID) (DisplayPicture, error)
	GetPaymentByReferenceID(ctx context.Context, referenceID string) (Payment, error)
	GetPaymentDetailsByID(ctx context.Context, id uuid.UUID) (Payment, error)
	GetPaymentTitleByID(ctx context.Context, id uuid.UUID) (TitleDeed, error)
	GetPaymentsByStatus(ctx context.Context, status string) ([]Payment, error)
	GetSupportDocByEmail(ctx context.Context, email string) (SupportDoc, error)
	GetSupportingDocById(ctx context.Context, id uuid.UUID) (SupportDoc, error)
	GetSupportingDocsByVerification(ctx context.Context, verification string) ([]SupportDoc, error)
	GetTitleByEmail(ctx context.Context, email string) (TitleDeed, error)
	GetTitlesByEmail(ctx context.Context, email string) ([]TitleDeed, error)
	UpdateDisplayPictureByID(ctx context.Context, arg UpdateDisplayPictureByIDParams) (DisplayPicture, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdateSupportDocVerificationById(ctx context.Context, arg UpdateSupportDocVerificationByIdParams) (SupportDoc, error)
	UpdateTitleVerificationById(ctx context.Context, arg UpdateTitleVerificationByIdParams) (TitleDeed, error)
}

var _ Querier = (*Queries)(nil)
