// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sql

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateSupportDoc(ctx context.Context, arg CreateSupportDocParams) (SupportDoc, error)
	CreateTitle(ctx context.Context, arg CreateTitleParams) (Title, error)
	CreateUser(ctx context.Context, email string) (User, error)
	GetPaymentByReferenceID(ctx context.Context, referenceID string) (Payment, error)
	GetPaymentDetailsByID(ctx context.Context, id uuid.UUID) (Payment, error)
	GetPaymentTitleByID(ctx context.Context, id uuid.UUID) (Title, error)
	GetPaymentsByStatus(ctx context.Context, status string) ([]Payment, error)
	GetSupportDocByEmail(ctx context.Context, email string) (SupportDoc, error)
	GetTitleByEmail(ctx context.Context, email string) (Title, error)
	GetUser(ctx context.Context, email string) (User, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdateSupportDocByEmail(ctx context.Context, arg UpdateSupportDocByEmailParams) (SupportDoc, error)
	UpdateTitleByEmail(ctx context.Context, arg UpdateTitleByEmailParams) (Title, error)
	UpdateTitleVerificationById(ctx context.Context, arg UpdateTitleVerificationByIdParams) (Title, error)
	UpdateUserByEmail(ctx context.Context, arg UpdateUserByEmailParams) (User, error)
}

var _ Querier = (*Queries)(nil)
