// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sql

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateSupportDoc(ctx context.Context, arg CreateSupportDocParams) (SupportDoc, error)
	CreateTitle(ctx context.Context, arg CreateTitleParams) (Title, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetEmailSupportDoc(ctx context.Context, email string) (SupportDoc, error)
	GetEmailTitle(ctx context.Context, email string) (Title, error)
	GetPaymentByReferenceID(ctx context.Context, referenceID string) (Payment, error)
	GetPaymentDetailsByID(ctx context.Context, id uuid.UUID) (Payment, error)
	GetPaymentTitleByID(ctx context.Context, id uuid.UUID) (Title, error)
	GetPaymentsByStatus(ctx context.Context, status string) ([]Payment, error)
	GetUser(ctx context.Context, walletAddress string) (User, error)
	UpdateEmailSupportDoc(ctx context.Context, arg UpdateEmailSupportDocParams) (SupportDoc, error)
	UpdateEmailTitle(ctx context.Context, arg UpdateEmailTitleParams) (Title, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdateTitleVerification(ctx context.Context, arg UpdateTitleVerificationParams) (Title, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
