// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: title.sql

package sql

import (
	"context"
)

const createTitle = `-- name: CreateTitle :one
INSERT INTO titles (
  title, email, wallet_address
) VALUES (
  $1, $2, $3
) RETURNING id, title, verification, email, wallet_address, created_at, updated_at
`

type CreateTitleParams struct {
	Title         string `json:"title"`
	Email         string `json:"email"`
	WalletAddress string `json:"wallet_address"`
}

func (q *Queries) CreateTitle(ctx context.Context, arg CreateTitleParams) (Title, error) {
	row := q.db.QueryRowContext(ctx, createTitle, arg.Title, arg.Email, arg.WalletAddress)
	var i Title
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Verification,
		&i.Email,
		&i.WalletAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
