// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: title.sql

package sql

import (
	"context"

	"github.com/google/uuid"
)

const createTitle = `-- name: CreateTitle :one
INSERT INTO titles (
  title, email
) VALUES (
  $1, $2
) RETURNING id, title, verification, email, created_at, updated_at
`

type CreateTitleParams struct {
	Title string `json:"title"`
	Email string `json:"email"`
}

func (q *Queries) CreateTitle(ctx context.Context, arg CreateTitleParams) (Title, error) {
	row := q.db.QueryRowContext(ctx, createTitle, arg.Title, arg.Email)
	var i Title
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Verification,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTitleByEmail = `-- name: GetTitleByEmail :one
SELECT id, title, verification, email, created_at, updated_at FROM titles
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetTitleByEmail(ctx context.Context, email string) (Title, error) {
	row := q.db.QueryRowContext(ctx, getTitleByEmail, email)
	var i Title
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Verification,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTitleByEmail = `-- name: UpdateTitleByEmail :one
UPDATE titles SET title = $1, verification = $2
WHERE email = $3
RETURNING id, title, verification, email, created_at, updated_at
`

type UpdateTitleByEmailParams struct {
	Title        string `json:"title"`
	Verification string `json:"verification"`
	Email        string `json:"email"`
}

func (q *Queries) UpdateTitleByEmail(ctx context.Context, arg UpdateTitleByEmailParams) (Title, error) {
	row := q.db.QueryRowContext(ctx, updateTitleByEmail, arg.Title, arg.Verification, arg.Email)
	var i Title
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Verification,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTitleVerificationById = `-- name: UpdateTitleVerificationById :one
UPDATE titles SET verification = $1
WHERE id = $2
RETURNING id, title, verification, email, created_at, updated_at
`

type UpdateTitleVerificationByIdParams struct {
	Verification string    `json:"verification"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateTitleVerificationById(ctx context.Context, arg UpdateTitleVerificationByIdParams) (Title, error) {
	row := q.db.QueryRowContext(ctx, updateTitleVerificationById, arg.Verification, arg.ID)
	var i Title
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Verification,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
