// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: upload.sql

package sql

import (
	"context"
	"database/sql"
)

const createUpload = `-- name: CreateUpload :execresult
INSERT INTO uploads (
  email, public_address, type, uri, verification
) VALUES (
  $1, $2, $3, $4, $5
)
`

type CreateUploadParams struct {
	Email         string `json:"email"`
	PublicAddress string `json:"public_address"`
	Type          string `json:"type"`
	Uri           string `json:"uri"`
	Verification  string `json:"verification"`
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUpload,
		arg.Email,
		arg.PublicAddress,
		arg.Type,
		arg.Uri,
		arg.Verification,
	)
}
