name: Fly
on:
  push:
    branches:
      - staging
jobs:
  deploy:
    name: Staging api
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd Server && flyctl deploy --config fly-staging.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_STAGING_API_TOKEN }}
