name: Test
on: [push]
jobs:
  deploy:
    name: test-copod
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:latest
        # Provide credentials for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: demo1234
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-retries 5
    steps:
    # Checkout code
    - name: checkout code
      uses: actions/checkout@v4
    # Setup go
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.22
    - name: setup Postgresql
      run: |
        sudo apt-get -yqq install postgresql-client
        psql --version
        PGPASSWORD=demo1234 psql -h localhost -U postgres -c 'DROP DATABASE IF EXISTS test;'
        PGPASSWORD=demo1234 psql -h localhost -U postgres -c 'CREATE DATABASE test;'
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: cd SmartContract && npm ci
    - name: test
      run: make test-copod
